name: Deploy

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - '.gitignore'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'production'
        type: choice
        options:
          - production

jobs:
  deploy:
    name: Deploy to Server
    runs-on: linux
    steps:
      - name: Checkout code
        run: |
          SERVER_HOST=$(echo "${{ github.server_url }}" | sed 's|https://||' | sed 's|http://||')
          git clone --depth 1 --branch ${{ github.ref_name }} http://oauth2:${{ secrets.GITHUB_TOKEN }}@${SERVER_HOST}/${{ github.repository }}.git .

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

      - name: Deploy via SSH
        env:
          SSH_HOST: ${{ secrets.DEPLOY_HOST }}
          SSH_USER: ${{ secrets.DEPLOY_USER }}
          SSH_PORT: ${{ secrets.DEPLOY_SSH_PORT || '22' }}
          DEPLOY_PATH: ${{ vars.DEPLOY_PATH }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          API_PORT: ${{ vars.API_PORT || '3001' }}
          WEB_PORT: ${{ vars.WEB_PORT || '3000' }}
        run: |
          ssh -i ~/.ssh/deploy_key -p ${SSH_PORT:-22} -o StrictHostKeyChecking=no -o BatchMode=yes ${SSH_USER}@${SSH_HOST} << DEPLOY_SCRIPT
          set -e
          echo "🚀 Starting deployment..."
          
          # Navigate to project directory
          cd ${DEPLOY_PATH}
          
          # Pull latest code
          echo "⬇️ Pulling latest code..."
          git pull origin main
          
          # Backup database
          echo "📦 Creating database backup..."
          docker compose -f docker-compose.prod.yml exec -T db pg_dump -U ${POSTGRES_USER} ${POSTGRES_DB} > backup_\$(date +%Y%m%d_%H%M%S).sql 2>/dev/null || echo "No existing DB to backup"
          
          # Build and restart services
          echo "🔨 Building and restarting services..."
          docker compose -f docker-compose.prod.yml up -d --build --force-recreate
          
          # Wait for services to start
          echo "⏳ Waiting for services..."
          sleep 20
          
          # Run database migrations
          echo "🔄 Running migrations..."
          docker compose -f docker-compose.prod.yml exec -T api npx prisma migrate deploy || echo "Migration skipped"
          
          # Health checks
          echo "🏥 Running health checks..."
          
          if curl -sf http://localhost:${API_PORT:-3001}/health > /dev/null 2>&1 || curl -sf http://localhost:${API_PORT:-3001}/ > /dev/null 2>&1; then
            echo "✅ API is healthy"
          else
            echo "⚠️ API check inconclusive, checking logs..."
            docker compose -f docker-compose.prod.yml logs --tail=20 api
          fi
          
          if curl -sf http://localhost:${WEB_PORT:-3000}/ > /dev/null 2>&1; then
            echo "✅ Web is healthy"
          else
            echo "⚠️ Web check inconclusive, checking logs..."
            docker compose -f docker-compose.prod.yml logs --tail=20 web
          fi
          
          # Cleanup
          echo "🧹 Cleaning up old images..."
          docker image prune -f
          
          # Keep only last 5 backups
          ls -t backup_*.sql 2>/dev/null | tail -n +6 | xargs -r rm
          
          echo "✅ Deployment complete!"
          DEPLOY_SCRIPT

      - name: Notify Discord - Success
        if: success() && vars.DISCORD_WEBHOOK_URL != ''
        run: |
          curl -H "Content-Type: application/json" \
            -d '{"embeds": [{"title": "✅ Déploiement réussi", "color": 5763719, "description": "Cloud Proxmox déployé avec succès", "footer": {"text": "Commit: ${{ github.sha }}"}}]}' \
            ${{ vars.DISCORD_WEBHOOK_URL }} || true

      - name: Notify Discord - Failure
        if: failure() && vars.DISCORD_WEBHOOK_URL != ''
        run: |
          curl -H "Content-Type: application/json" \
            -d '{"embeds": [{"title": "❌ Déploiement échoué", "color": 15548997, "description": "Vérifiez les logs GitHub Actions", "footer": {"text": "Commit: ${{ github.sha }}"}}]}' \
            ${{ vars.DISCORD_WEBHOOK_URL }} || true
