name: Deploy

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

env:
  REGISTRY: ${{ vars.DOCKER_REGISTRY || 'docker.io' }}
  API_IMAGE: ${{ vars.DOCKER_REGISTRY || 'docker.io' }}/cloud-proxmox-api
  WEB_IMAGE: ${{ vars.DOCKER_REGISTRY || 'docker.io' }}/cloud-proxmox-web

jobs:
  build-and-push:
    name: Build and Push Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Build and push API
        uses: docker/build-push-action@v5
        with:
          context: ./api
          push: true
          tags: |
            ${{ env.API_IMAGE }}:${{ steps.version.outputs.VERSION }}
            ${{ env.API_IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Web
        uses: docker/build-push-action@v5
        with:
          context: ./web
          push: true
          tags: |
            ${{ env.WEB_IMAGE }}:${{ steps.version.outputs.VERSION }}
            ${{ env.WEB_IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            cd ${{ vars.DEPLOY_PATH || '/opt/cloud-proxmox' }}
            
            # Pull latest images
            docker compose pull
            
            # Restart services
            docker compose up -d --remove-orphans
            
            # Clean up old images
            docker image prune -f
            
            # Health check
            sleep 10
            curl -f http://localhost:3002/ || exit 1
            curl -f http://localhost:3000/ || exit 1
            
            echo "Deployment successful!"
