name: Deploy

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

env:
  REGISTRY: ${{ vars.DOCKER_REGISTRY || 'ghcr.io' }}
  API_IMAGE: ${{ vars.DOCKER_REGISTRY || 'ghcr.io' }}/${{ github.repository }}-api
  WEB_IMAGE: ${{ vars.DOCKER_REGISTRY || 'ghcr.io' }}/${{ github.repository }}-web

jobs:
  # ===================
  # Build & Push Images
  # ===================
  build-and-push:
    name: Build and Push Images
    runs-on: linux
    outputs:
      version: ${{ steps.version.outputs.VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract version
        id: version
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=latest" >> $GITHUB_OUTPUT
          fi

      - name: Build and push API
        uses: docker/build-push-action@v5
        with:
          context: ./api
          push: true
          tags: |
            ${{ env.API_IMAGE }}:${{ steps.version.outputs.VERSION }}
            ${{ env.API_IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

      - name: Build and push Web
        uses: docker/build-push-action@v5
        with:
          context: ./web
          push: true
          tags: |
            ${{ env.WEB_IMAGE }}:${{ steps.version.outputs.VERSION }}
            ${{ env.WEB_IMAGE }}:latest
          build-args: |
            NEXT_PUBLIC_API_URL=${{ secrets.PUBLIC_API_URL }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

  # ===================
  # Deploy to Server
  # ===================
  deploy:
    name: Deploy to ${{ github.event.inputs.environment || 'production' }}
    runs-on: linux
    needs: build-and-push
    environment: ${{ github.event.inputs.environment || 'production' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: ${{ secrets.DEPLOY_SSH_PORT || 22 }}
          script: |
            set -e
            echo "🚀 Starting deployment..."
            
            # Navigate to project
            cd ${{ vars.DEPLOY_PATH || '/docker/cloud_proxmox' }}
            
            # Backup current state
            echo "📦 Creating backup..."
            docker compose exec -T db pg_dump -U cloud cloud_proxmox > backup_$(date +%Y%m%d_%H%M%S).sql || true
            
            # Pull latest images
            echo "⬇️ Pulling latest images..."
            docker compose -f docker-compose.prod.yml pull
            
            # Run database migrations
            echo "🔄 Running migrations..."
            docker compose -f docker-compose.prod.yml exec -T api npx prisma migrate deploy || true
            
            # Restart services with zero downtime
            echo "🔄 Restarting services..."
            docker compose -f docker-compose.prod.yml up -d --remove-orphans
            
            # Wait for services
            echo "⏳ Waiting for services..."
            sleep 15
            
            # Health checks
            echo "🏥 Running health checks..."
            
            # Check API
            if curl -sf http://localhost:3002/health > /dev/null 2>&1; then
              echo "✅ API is healthy"
            elif curl -sf http://localhost:3002/ > /dev/null 2>&1; then
              echo "✅ API is responding"
            else
              echo "❌ API health check failed"
              docker compose -f docker-compose.prod.yml logs --tail=50 api
              exit 1
            fi
            
            # Check Web
            if curl -sf http://localhost:3000/ > /dev/null 2>&1; then
              echo "✅ Web is healthy"
            else
              echo "❌ Web health check failed"
              docker compose -f docker-compose.prod.yml logs --tail=50 web
              exit 1
            fi
            
            # Cleanup old images
            echo "🧹 Cleaning up..."
            docker image prune -f
            
            echo "✅ Deployment successful!"

      - name: Notify Discord - Success
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
            -d '{"embeds": [{"title": "✅ Deployment Successful", "color": 5763719, "fields": [{"name": "Environment", "value": "${{ github.event.inputs.environment || '\''production'\'' }}", "inline": true}, {"name": "Version", "value": "${{ needs.build-and-push.outputs.version }}", "inline": true}], "footer": {"text": "${{ github.repository }}"}}]}' \
            ${{ secrets.DISCORD_WEBHOOK_URL }} || true

      - name: Notify Discord - Failure
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
            -d '{"embeds": [{"title": "❌ Deployment Failed", "color": 15548997, "description": "Deployment to ${{ github.event.inputs.environment || '\''production'\'' }} failed. Check the logs.", "footer": {"text": "${{ github.repository }}"}}]}' \
            ${{ secrets.DISCORD_WEBHOOK_URL }} || true

  # ===================
  # Rollback Job
  # ===================
  rollback:
    name: Rollback (Manual)
    runs-on: linux
    if: false  # Only run manually via workflow_dispatch
    steps:
      - name: Rollback via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            cd ${{ vars.DEPLOY_PATH || '/docker/cloud_proxmox' }}
            
            # Find latest backup
            LATEST_BACKUP=$(ls -t backup_*.sql | head -1)
            
            if [ -n "$LATEST_BACKUP" ]; then
              echo "Restoring from $LATEST_BACKUP..."
              docker compose exec -T db psql -U cloud cloud_proxmox < $LATEST_BACKUP
              echo "Rollback complete!"
            else
              echo "No backup found!"
              exit 1
            fi
